name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
- type: markdown
  attributes:
    value: "## Thank you for taking the time to fill out this bug report"

- type: dropdown
  id: operating-system
  attributes:
    label: Operating system
    description: "On what operating system are you trying to use Textstat? _[Other?](#issue_form_other)_"
    options:
      - Linux
      - Windows
      - MacOS
      - Other
  validations:
    required: true

- type: dropdown
  id: download
  attributes:
    label: Download source
    description: "Where to did you download/install Textstat from? _[Other?](#issue_form_other)_"
    options:
      - PyPi
      - GitHub clone
      - Conda Forge
      - Other
  validations:
    required: true

- type: dropdown
  id: python-distribution
  attributes:
    label: Python distribution
    description: "What Python distribution are you running. (Standard [Python](https://www.python.org/) is CPython). _[Other?](#issue_form_other)_"
    options:
      - CPython
      - Anaconda
      - IPython
      - Other
  validations:
    required: true

- type: input
  id: python-version
  attributes:
    label: Python version
    description: "What version of Python are you running? `python --version`"
    placeholder: "Python 3.9.6"
    value: "Python 3.9.6"
  validations:
    required: true

- type: textarea
  id: description
  attributes:
    label: What happened?
    description: "Describe in your own words the issue that you are having. What happened? What did you expect to happen?"
  validations:
    required: true

- type: textarea
  id: other
  attributes:
    label: Other information
    description: "Please provide any other information you feel is relevant. If you answered _other_ to the above selections, provide the information here."
  validations:
    required: true

- type: textarea
  id: test-case
  attributes:
    label: Failing tests
    description: "If possible, provide a failing test case that demonstrates the bug"
    value: |
      def test_the_bug_i_found():
          assert True
    render: python

- type: checkboxes
  attributes:
    label: Code of Conduct
    description: The Code of Conduct helps create a safe space for everyone. We require
      that everyone agrees to it.
    options:
      - label: I agree to follow this project's [Code of Conduct](https://github.com/textstat/community/blob/main/CODE_OF_CONDUCT.md)
        required: true